### ISSUE TITLE
发现--->推荐,向下滑动图片加载异常，闪烁，卡顿，然后多向下滑动几屏会crash

### ISSUE THREAD

**Issue by AmazingMachine** [fmtjava/flutter_eyepetizer#1]
测试设备是 pixel xl

其它模块体验很好，语言识别模块请求的权限有点多，估计是第3方库的原因。

同样是开发人员，我只能说您真是牛逼。

**Comment by fmtjava** [comment]
非常走心的总结

**Comment by fmtjava** [comment]
刚才测试了一下，发现推荐接口返回的图片太大了(接近1M)，导致内存爆掉了

**Comment by AmazingMachine** [comment]
Glide是不是没有支持flutter的版本，如果是Glide还可以避免这个闪退的情况

**Comment by fmtjava** [comment]
这块我在优化了，今天会更新一个版本，到时可以下载体验一下

**Comment by AmazingMachine** [comment]
> 这块我在优化了，今天会更新一个版本，到时可以下载体验一下

刚才还有位新朋友在问我flutter版的eyepetizer的链接估计过会您的项目就会star+1

**Comment by fmtjava** [comment]
> > 这块我在优化了，今天会更新一个版本，到时可以下载体验一下
> 
> 刚才还有位新朋友在问我flutter版的eyepetizer的链接估计过会您的项目就会star+1

新版已经发了

**Comment by AmazingMachine** [comment]
![device-2020-07-07-101912](https://user-images.githubusercontent.com/28883779/86691370-5632e180-c03b-11ea-952f-b59ea5c6ea54.png)
测试过了，作者完美的解决了这个问题，就是那个蓝色的加载进度progressbar+灰色的background配色不是特别的完美，其实不用那个蓝色的加载进度progressbar因为图片的加载速度本来就比较快。

**Comment by william-xue** [comment]
<img width="724" alt="截屏2021-03-03 下午10 32 47" src="https://user-images.githubusercontent.com/20151622/109821574-11feec00-7c71-11eb-82ef-8805a97f8f08.png">
之前跑过你项目 现在po====vy=不行看=

**Comment by fmtjava** [comment]
前阵子升级Flutter SDK版本，label是高版本推荐使用的，你可以升级一下你的本地Flutter SDK
