### ISSUE TITLE
banner显示细节问题

### ISSUE THREAD

**Issue by EvanEvil** [fmtjava/flutter_eyepetizer#2]
发现个问题，banner加载的时候，显示出来的效果是先加载出矩形图片，然后再裁剪出圆角，我的解决方案是去掉BoxDecoration的borderRadius，而是在Stack外边包裹一个ClipRRect来裁剪出圆角

**Comment by fmtjava** [comment]
非常细心，去掉BoxDecoration的borderRadius，而是在Stack外边包裹一个ClipRRect来裁剪出圆角，此方法可行
