### ISSUE TITLE
这里改好了 

### ISSUE THREAD

**Issue by william-xue** [fmtjava/flutter_eyepetizer#5]
_bottomItem(String title, String normalIcon, String selectIcon) {
    return BottomNavigationBarItem(
      icon: Image.asset(normalIcon, width: 24, height: 24),
      activeIcon: Image.asset(selectIcon, width: 24, height: 24),
      // title:title);
      title: Padding(
          padding: EdgeInsets.only(top: 5),
          child: Text(title,
              style: TextStyle(color: Color(0xff000000), fontSize: 14))),
    );
  }

**Comment by fmtjava** [comment]
前阵子升级Flutter SDK版本，label是1.12版本推荐使用的，你可以升级一下你的本地Flutter SDK
