### ISSUE TITLE
大佬， customer_video_controlls.dart 里面自定义播放空间找不到

### ISSUE THREAD

**Issue by smartdriver001** [fmtjava/flutter_eyepetizer#8]
首先感谢作者的无私奉献。

我clone 下来后直接跑 会出现这种情况
提示的是 

import 'package:chewie/src/material_progress_bar.dart';
import 'package:chewie/src/utils.dart';

这两个文件找不到，请问我应该怎么解决？ 

关于 getx 在整个项目中 有哪些用到？ 能否基于getx 构建一个 eyepetizer

**Comment by fmtjava** [comment]
clone 下来后请Pub get三个地方，Flutter_Eyepetizer工程下的pubspec.yaml，component目录下各个组件的pubspec.yaml，module目录下各个业务组件的pubspec.yaml，然后运行即可
![image](https://user-images.githubusercontent.com/16126424/130713705-2c3b0950-e2a1-4679-83b8-2d6e7b8e18ea.png)
