### ISSUE TITLE
带佬 运行不了啊

### ISSUE THREAD

**Issue by Mikebanana** [fmtjava/flutter_eyepetizer#9]
../../flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.6.5/lib/src/internals/indicator_wrap.dart:632:9: Error: A value of type 'ValueNotifier<Enum>' can't be assigned to a variable of type 'ValueNotifier<V>'.
     - 'ValueNotifier' is from 'package:flutter/src/foundation/change_notifier.dart' ('../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart').
            ? refresher.controller.headerMode
            ^
    Failed to package /Users/liyu/Downloads/Flutter_Eyepetizer-master.

**Comment by fmtjava** [comment]
flutter sdk用了那个版本

**Comment by Mikebanana** [comment]
flutter_macos_2.5.0-stable

**Comment by fmtjava** [comment]
目前这个项目是基于flutter_macos_2.0.1-stable开发的，估计是版本升级适配问题，我晚点下载新版sdk看一下

**Comment by Mikebanana** [comment]
ojbk

**Comment by bill-bil** [comment]
就这东西还学人家收费？

**Comment by Mikebanana** [comment]
> 就这东西还学人家收费？

谁收费了？

**Comment by fmtjava** [comment]
已经对flutter_macos_2.5.0-stable做适配了，可以同步一下，看看有没有问题
